<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>ssh on Miro&#39;s World</title>
    <link>https://miroadamy.com/tags/ssh/</link>
    <description>Recent content in ssh on Miro&#39;s World</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en</language>
    <lastBuildDate>Tue, 12 May 2020 22:34:38 +0800</lastBuildDate><atom:link href="https://miroadamy.com/tags/ssh/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>Using SSH keys with multiple Bitbucket accounts</title>
      <link>https://miroadamy.com/posts/2020-05-12-bitbucket-keys/</link>
      <pubDate>Tue, 12 May 2020 22:34:38 +0800</pubDate>
      
      <guid>https://miroadamy.com/posts/2020-05-12-bitbucket-keys/</guid>
      <description>I have been using Bitbucket since 2012, long before my company moved from in-house hosted server running Gitolite and in-house instances of FishEye and Crucible to cloud based source control on Bitbucket Cloud. As legacy I was using my personal login with my gmail account as my Bitbucket identity.
With merge of 3 companies in 2018 and rebranding as Pivotree, we are in process of streamlining the identity management and using SSO for identification.</description>
    </item>
    
    <item>
      <title>How to solve &#39;Agent admitted failure to sign using the key&#39;</title>
      <link>https://miroadamy.com/posts/2015-05-22-ssh-issue/</link>
      <pubDate>Fri, 22 May 2015 11:22:48 +0800</pubDate>
      
      <guid>https://miroadamy.com/posts/2015-05-22-ssh-issue/</guid>
      <description>After re-creating the SSH key, I got the above error from Gitolite.
Full trace:
âžœ TWC ssh -v thinkwrap@pensieve.thinkwrap.com OpenSSH_5.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013 debug1: Reading configuration data /etc/ssh/ssh_config debug1: Applying options for * debug1: Connecting to pensieve.thinkwrap.com [24.137.198.18] port 22. debug1: Connection established. debug1: identity file /home/thinkwrap/.ssh/identity type -1 debug1: identity file /home/thinkwrap/.ssh/identity-cert type -1 debug1: identity file /home/thinkwrap/.ssh/id_rsa type 1 debug1: identity file /home/thinkwrap/.ssh/id_rsa-cert type -1 debug1: identity file /home/thinkwrap/.</description>
    </item>
    
    <item>
      <title>GitHub identity mixup</title>
      <link>https://miroadamy.com/posts/2012-04-15-github/</link>
      <pubDate>Sun, 15 Apr 2012 11:22:48 +0800</pubDate>
      
      <guid>https://miroadamy.com/posts/2012-04-15-github/</guid>
      <description>After I created the ThinkWrap GitHub account and uploaded the public key, this key got somehow bound to GitHub identity &amp;lsquo;madamy&amp;rsquo;
I had to add user madamy to my public GitHub repo - where I keep the dot-files - https://github.com/radegast/dotvim
This may be an issue for people that have their own private accounts - the key management is the key.
This article is useful:
 http://sealedabstract.com/code/github-ssh-with-multiple-identities-the-slightly-more-definitive-guide/ http://net.tutsplus.com/tutorials/tools-and-tips/how-to-work-with-github-and-multiple-accounts/  Alternative Use https for forking , instead read/write ssh.</description>
    </item>
    
    <item>
      <title>How to fix the remote origin from read only</title>
      <link>https://miroadamy.com/posts/2012-03-21-remote-origin/</link>
      <pubDate>Wed, 21 Mar 2012 11:22:48 +0800</pubDate>
      
      <guid>https://miroadamy.com/posts/2012-03-21-remote-origin/</guid>
      <description>Issue In dotvim repo, I used readonly URL for cloning the repository. Now I have created local branch ( linux-vm ) to track Linux specific font settings and need them to push up.
After creating new SSH pair and adding to GitHub, does not work
[tkuser@cplx-dev-vf .vim]$ git status # On branch linux-vm nothing to commit (working directory clean)[tkuser@cplx-dev-vf .vim]$ git push origin linux-vm fatal: remote error: You can&amp;#39;t push to git://github.</description>
    </item>
    
  </channel>
</rss>
